name: first_flutter_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  http: ^1.4.0
  fl_chart: ^1.0.0
  flutter_dotenv: ^5.0.2
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  confetti: ^0.8.0
  firebase_auth: ^6.0.0
  shared_preferences: ^2.0.15
  timezone: ^0.10.1
  shimmer: ^3.0.0
  provider: ^6.0.0
  palette_generator: ^0.3.2
  syncfusion_flutter_charts: ^29.1.39
  share_plus: ^10.0.0
  flutter_speed_dial: ^7.0.0
  retry: ^3.1.0
  flutter_local_notifications: ^19.2.1
  connectivity_plus: ^6.1.4
  flutter_markdown: ^0.6.15
  animated_text_kit: ^4.2.1
  lottie: ^2.7.0
  auto_size_text: ^3.0.0
  firebase_analytics: ^12.0.0
  firebase_crashlytics: ^5.0.0
  shimmer_animation: ^2.1.0
  rive: ^0.12.4
  flutter_animate: ^4.5.2
  flutter_staggered_animations: ^1.1.1
  glassmorphism: ^3.0.0
  liquid_progress_indicator_v2: ^0.5.0
  url_launcher: ^6.1.11
  flutter_screenutil: ^5.8.4
  flutter_shaders: ^0.1.0
  particles_flutter: ^0.1.1
  flutter_3d_carousel: ^2.1.0
  sliding_up_panel: ^2.0.0
  spoiler_widget: ^1.0.0
  flutter_3d_controller: ^1.0.1
  vibration: ^2.0.0
  vector_math: ^2.1.4
  flutter_spinkit: ^5.1.0


dependency_overrides:
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.0
  pigeon: ^20.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/animations/scroll.json
    - assets/animations/excited.json
    - assets/animations/normal.json
    - assets/animations/happy.json
    - assets/animations/morty.json
    - assets/animations/dreams.json
    - assets/animations/man.json
    - assets/animations/Sleeping.json
    - assets/animations/cosmic_back.json
    - assets/animations/sleep_moon.json
    - assets/animations/cosmos.json
    - assets/animations/no_data.json
    - assets/animations/no_connection.json
    - assets/animations/error.json
    - assets/animations/top.json
    - assets/animations/border.json
    - assets/animations/doctor.json
    - assets/animations/animal.json
    - assets/animations/cat.json
    - assets/animations/cosmic_galaxy.json
    - assets/animations/travelbackground.json
    - assets/animations/trainbackground2.json
    - assets/animations/treesbackground.json
    - assets/animations/rainbackground.json
    - assets/animations/spacebackground.json
    - assets/animations/trainbackground.json
    - assets/animations/ai_brain.json
    - assets/animations/button.json
    - assets/animations/dreamy_night.json
    - assets/animations/floating_stars.json
    - assets/images/sleepback2.png
    - assets/images/fullmoon.svg
    - assets/images/cloud.png
    - assets/images/analyzelogo.svg
    - assets/images/phonelogo.svg
    - assets/images/yogalogo.svg
    - assets/images/coffeecup.svg
    - assets/images/chat_ai_background.jpg
    - assets/images/logo.svg
    - assets/images/Image1.png
    - assets/images/Frame.svg
    - assets/images/Frame4.svg
    - assets/images/NavigateLeft.svg
    - assets/images/Facebook.svg
    - assets/images/Google.svg
    - assets/images/WelcomeImage.jpg
    - assets/images/logo2.svg
    - assets/images/UnionFrame.svg
    - assets/images/Widget1.svg
    - assets/images/Widget2.svg
    - assets/images/Widget3.svg
    - assets/images/Widget4.svg
    - assets/images/Widget5.svg
    - assets/images/Widget6.svg
    - assets/images/apple.svg
    - assets/images/woman.svg
    - assets/images/dailyframe1.svg
    - assets/images/dailyframe2.svg
    - assets/images/dailyframe3.svg
    - assets/images/image20.svg
    - assets/images/image21.svg
    - assets/images/homeIcon.svg
    - assets/images/sleepIcon.svg
    - assets/images/meditateIcon.svg
    - assets/images/musicIcon.svg
    - assets/images/profileIcon.svg
    - assets/images/container1.svg
    - assets/images/container2.svg
    - assets/images/sun.svg
    - assets/images/heart.svg
    - assets/images/download.svg
    - assets/images/heartIcon.svg
    - assets/images/headphoneIcon.svg
    - assets/images/all.svg
    - assets/images/anxious.svg
    - assets/images/kids.svg
    - assets/images/my.svg
    - assets/images/sleep.svg
    - assets/images/frame105.svg
    - assets/images/frame106.svg
    - assets/images/frame107.svg
    - assets/images/calm.svg
    - assets/images/anxiet.svg
    - assets/images/backframe1.svg
    - assets/images/backframe2.svg
    - assets/images/backframe3.svg
    - assets/images/backframe4.svg
    - assets/images/removeIcon.svg
    - assets/images/navigaterightTime.svg
    - assets/images/navigateleftTime.svg
    - assets/images/home105.svg
    - assets/images/sleepframe.svg
    - assets/images/cloud.svg
    - assets/images/birds.svg
    - assets/images/sleepframe2.svg
    - assets/images/sleepframe3.svg
    - assets/images/sleepmoon.png
    - assets/images/happycloud.svg
    - assets/images/happybirds.svg
    - assets/images/bowlmoon.svg
    - assets/images/pinkmoon.svg
    - assets/images/happycloud2.svg
    - assets/images/nightframe.svg
    - assets/images/nightframe2.svg
    - assets/images/removeIcon2.svg
    - assets/images/splash_image.jpg
    - assets/images/coffeeIcon.svg

  fonts:
    - family: AirbnbCereal
      fonts:
        - asset: assets/fonts/AirbnbCerealBook.ttf
          weight: 400

    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay-Italic.ttf
          style: italic
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 700

    - family: HelveticaNeueRegular
      fonts:
        - asset: assets/fonts/HelveticaNeueLTStd-Rg.ttf
          weight: 400

    - family: HelveticaNeueBold
      fonts:
        - asset: assets/fonts/HelveticaNeueLTStd-Bd.otf
          weight: 700

    - family: ComfortaaLight
      fonts:
        - asset: assets/fonts/Comfortaa-Light.ttf
          weight: 700

    - family: ComfortaaBold
      fonts:
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 700

    - family: ComfortaaRegular
      fonts:
        - asset: assets/fonts/Comfortaa-Regular.ttf
          weight: 700

    - family: nunitoSansBold
      fonts:
        - asset: assets/fonts/NunitoSans-Bold.ttf
          weight: 700

    - family: nunitoSansRegular
      fonts:
        - asset: assets/fonts/NunitoSans-Light.ttf
          weight: 700

  shaders:
    - shaders/hologram.frag

flutter_native_splash:
  image: assets/images/splash_image.jpg
  android: true
  ios: true
