// Autogenerated from Pigeon (v20.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "GeneratedFirebaseAuth.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray<id> *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}

static id GetNullableObjectAtIndex(NSArray<id> *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@interface nullGeneratedFirebaseAuthPigeonCodecReader : FlutterStandardReader
@end
@implementation nullGeneratedFirebaseAuthPigeonCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface nullGeneratedFirebaseAuthPigeonCodecWriter : FlutterStandardWriter
@end
@implementation nullGeneratedFirebaseAuthPigeonCodecWriter
- (void)writeValue:(id)value {
{
    [super writeValue:value];
  }
}
@end

@interface nullGeneratedFirebaseAuthPigeonCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation nullGeneratedFirebaseAuthPigeonCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[nullGeneratedFirebaseAuthPigeonCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[nullGeneratedFirebaseAuthPigeonCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *nullGetGeneratedFirebaseAuthCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    nullGeneratedFirebaseAuthPigeonCodecReaderWriter *readerWriter = [[nullGeneratedFirebaseAuthPigeonCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}
void SetUpAuthApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<AuthApi> *api) {
  SetUpAuthApiWithSuffix(binaryMessenger, api, @"");
}

void SetUpAuthApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<AuthApi> *api, NSString *messageChannelSuffix) {
  messageChannelSuffix = messageChannelSuffix.length > 0 ? [NSString stringWithFormat: @".%@", messageChannelSuffix] : @"";
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.first_flutter_app.AuthApi.getPlatformVersion", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetGeneratedFirebaseAuthCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getPlatformVersionWithError:)], @"AuthApi api (%@) doesn't respond to @selector(getPlatformVersionWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSString *output = [api getPlatformVersionWithError:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
