// Autogenerated from Pigeon (v20.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by all APIs.
NSObject<FlutterMessageCodec> *nullGetGeneratedFirebaseAuthCodec(void);

@protocol AuthApi
/// @return `nil` only when `error != nil`.
- (nullable NSString *)getPlatformVersionWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpAuthApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<AuthApi> *_Nullable api);

extern void SetUpAuthApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<AuthApi> *_Nullable api, NSString *messageChannelSuffix);

NS_ASSUME_NONNULL_END
