// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfcXlpZnP9KddTgzzpatJ0hPvcQNBhAr0',
    appId: '1:394155869139:web:3cb0825c15b4a353442526',
    messagingSenderId: '394155869139',
    projectId: 'sleep-moon-973d5',
    authDomain: 'sleep-moon-973d5.firebaseapp.com',
    storageBucket: 'sleep-moon-973d5.firebasestorage.app',
    measurementId: 'G-982406MBBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVTz_9tBkGPfbu9oGOC-vkLuwxg-BcIk8',
    appId: '1:394155869139:android:a4c777a65102d81c442526',
    messagingSenderId: '394155869139',
    projectId: 'sleep-moon-973d5',
    storageBucket: 'sleep-moon-973d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlLtmgq5UPNhMYhywdLxTC_dGtNkPe9zU',
    appId: '1:394155869139:ios:b94951f238f363b5442526',
    messagingSenderId: '394155869139',
    projectId: 'sleep-moon-973d5',
    storageBucket: 'sleep-moon-973d5.firebasestorage.app',
    iosBundleId: 'com.AhmadSaad.firstFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlLtmgq5UPNhMYhywdLxTC_dGtNkPe9zU',
    appId: '1:394155869139:ios:64b5e073d34ce033442526',
    messagingSenderId: '394155869139',
    projectId: 'sleep-moon-973d5',
    storageBucket: 'sleep-moon-973d5.firebasestorage.app',
    iosBundleId: 'com.example.firstFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfcXlpZnP9KddTgzzpatJ0hPvcQNBhAr0',
    appId: '1:394155869139:web:c6702f9dee54a8a4442526',
    messagingSenderId: '394155869139',
    projectId: 'sleep-moon-973d5',
    authDomain: 'sleep-moon-973d5.firebaseapp.com',
    storageBucket: 'sleep-moon-973d5.firebasestorage.app',
    measurementId: 'G-N34JJLSGS8',
  );
}
